#release
FROM node:19.8.1-buster-slim AS release
RUN apt-get update && apt-get install -y openjdk-11-jre-headless && rm -rf /var/lib/apt/lists/*

WORKDIR /readers-lounge/frontend
COPY package*.json ./
COPY . .
RUN npm install
EXPOSE 80
RUN npm run build

CMD ["npm", "start"]
