openapi: 3.0.0
info:
  version: 1.0.0
  title: ReadersLounge API
  description: ReadersLounge API
servers:
  - url: "http://localhost:8080"
paths:
  /signup:
    post:
      summary:  create new user
      operationId: signup
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/ReqSignupBody"
        required: true
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ResSignupBody"
components:
  schemas:
    ReqSignupBody:
      properties:
        username:
          type: string
        identifier:
          type: string
        credential:
          type: string
    ResSignupBody:
      properties:
        identifier:
          type: string
        credential:
          type: string
    
                  
