openapi: 3.0.0
info:
  version: 1.0.0
  title: ReadersLounge API
  description: ReadersLounge API
servers:
  - url: "http://localhost:8080"
paths:
  /csrftoken:
    get:
      summary: get csrf token
      operationId: csrftoken
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ResCsrfToken"
  /signup:
    post:
      summary:  create new user
      operationId: signup
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/ReqSignupBody"
        required: true
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ResSignupBody"
  /login:
    post:
      summary: login
      operationId: login
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/ReqLoginBody"
        required: true
      responses:
        "200":
          description: OK
  /logout:
    post:
      summary: logout
      operationId: logout
      requestBody:
        content:
          application/json:
            schema:
              type: object
      responses:
        "200":
          description: OK
      
components:
  securitySchemes:
    X-CSRF-TOKEN:
      type: apiKey
      name: X-CSRF-TOKEN
      in: header
  schemas:
    ResCsrfToken:
      properties:
        csrf_token:
          type: string
    ReqSignupBody:
      properties:
        username:
          type: string
        identifier:
          type: string
        credential:
          type: string
    ResSignupBody:
      properties:
        user_id:
          type: integer
    ReqLoginBody:
      properties:
          identifier:
            type: string
          credential:
            type: string
      
security:
  - X-CSRF-TOKEN: []
    
                  
