openapi: 3.0.0
info:
  version: 1.0.0
  title: ReadersLounge API
  description: ReadersLounge API
servers:
  - url: "http://localhost:8080"
paths:
  /csrftoken:
    get:
      security: []
      summary: get csrf token
      operationId: csrftoken
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ResCsrfToken"
  /signup:
    post:
      security:
        - X-CSRF-TOKEN: []
      summary:  create new user
      operationId: signup
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/ReqSignupBody"
        required: true
      responses:
        "201":
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/User"
  /login:
    post:
      security:
        - X-CSRF-TOKEN: []
      summary: login
      operationId: login
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/ReqLoginBody"
        required: true
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/User"
  /oauth/google/callback:
    get:
      security:
        - google_auth:
          - email
          - profile
        - state: []
      summary: Callback for Google OAuth
      operationId: google_oauth_callback
      parameters:
        - name: state
          in: query
          required: true
          description: State parameter for CSRF protection
          schema:
            type: string
        - name: code
          in: query
          required: true
          description: Authorization code returned by Google auth server
          schema:
            type: string
      responses:
        "302":
          description: Redirect to Home
  /logout:
    post:
      security:
        - X-CSRF-TOKEN: []
      summary: logout
      operationId: logout
      requestBody:
        content:
          application/json:
            schema:
              type: object
      responses:
        "200":
          description: OK
  /user:
    get:
      security:
        - X-CSRF-TOKEN: []
        - jwtAuth: []
      summary: get user
      operationId: get-login-user
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/User"
    put:
      security:
        - X-CSRF-TOKEN: []
        - jwtAuth: []
      summary: update user
      operationId: update-user
      requestBody:
        content:
          multipart/form-data:
            schema:
              $ref: "#/components/schemas/UpdateUserReqBody"
        required: true
      responses:
        "204":
          description: OK
                
  /user/{userId}:
    get:
      security:
        - X-CSRF-TOKEN: []
        - jwtAuth: []
      summary: get user by user_id
      operationId: get-user
      parameters:
        - name: userId
          in: path
          required: true
          description: Unique identifier of the user
          schema:
            type: integer
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/User"
    
  /posts:
    get:
      security:
        - X-CSRF-TOKEN: []
        - jwtAuth: []
      summary: get posts
      operationId: get-posts
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Post"
    post:
      security:
        - X-CSRF-TOKEN: []
        - jwtAuth: []
      summary: create post
      operationId: create-post
      requestBody:
        content:
          multipart/form-data:
            schema:
              $ref: "#/components/schemas/ReqCreatePostBody"
        required: true
      responses:
        "201":
          description: OK

  /posts/{postId}:
    delete:
      security:
        - X-CSRF-TOKEN: []
        - jwtAuth: []
      summary: delete a post
      operationId: delete-post
      parameters:
        - name: postId
          in: path
          required: true
          description: Unique identifier of the post to be deleted
          schema:
            type: integer
      responses:
        "204":
          description: OK, post deleted successfully
          
  /books:
    get:
      security:
        - X-CSRF-TOKEN: []
        - jwtAuth: []
      summary: fetch book data from RakutenAPI
      operationId: fetch-book-data
      parameters:
        - name: booksGenreId
          in: query
          description: ID to specify the genre in Rakuten Books
          schema:
            type: string
        - name: keyword
          in: query
          description: keyword to search books
          schema:
            type: string
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Book"
  
  /books-genres:
    get:
      security:
        - X-CSRF-TOKEN: []
        - jwtAuth: []
      summary: Get books genres
      operationId: get-books-genres
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/BookGenreNode"
  /chats:
    get:
      servers:
        - url: "ws://localhost:8080"
      security:
        - X-CSRF-TOKEN: []
        - jwtAuth: []
      summary: WebSocket Connection for chat
      operationId: chat-socket
      parameters:
        - name: room_id
          in: query
          required: true
          description: ID to specify the chat room
          schema:
            type: integer
      responses:
        "101":
          description: Switching Protocols
        "401":
          description: You don't have permission to access this room 
      x-websocket-doc:
        messageTypes:
          - type: "req-message"
            description: "Chat message sent by a user (schema: #/components/schemas/SendMessageReqBody)"
            payload:
              type: object
              properties:
                content:
                  type: string
                room_id:
                  type: int
          - type: "res-message"
            description: "Chat message recieve from a user (schema: #/components/schemas/Message)"
            payload:
              type: object
              properties:
                message_id:
                  type: int
                user_id:
                  type: int
                content:
                  type: string
                sent_at:
                  type: string
  /chat-rooms:
    get:
      security:
        - X-CSRF-TOKEN: []
        - jwtAuth: []
      summary: return users chat room list
      operationId: get-chat-rooms
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/ChatRoom"
    post:
      security:
        - X-CSRF-TOKEN: []
        - jwtAuth: []
      summary: create chat room
      operationId: create-chat-room
      requestBody:
        content:
          application/json:
            schema:
              type: "object"
              required:
                - "chat_partner_id"
              properties:
                chat_partner_id:
                  type: integer
      responses:
        "201":
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  room_id:
                    type: integer
              
  /messages:
    get:
      security:
        - X-CSRF-TOKEN: []
        - jwtAuth: []
      summary: return messages in a chat room
      operationId: get-messages
      parameters:
        - name: room_id
          in: query
          required: true
          description: ID to specify the chat room
          schema:
            type: integer
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Message"
  
  /follows:
    post:
      security:
        - X-CSRF-TOKEN: []
        - jwtAuth: []
      summary: create connection of following
      operationId: create-connection
      requestBody:
        content:
          application/json:
            schema:
              type: "object"
              required:
                - "target_user_id"
              properties:
                target_user_id:
                  type: integer
      responses:
        "201":
          description: OK
  /follows/{connectionId}:
    delete:
      security:
        - X-CSRF-TOKEN: []
        - jwtAuth: []
      summary: delete connection of following
      operationId: delete-connection
      parameters:
        - name: connectionId
          in: path
          required: true
          description: Unique identifier of the connection to be deleted
          schema:
            type: integer
      responses:
        "204":
          description: OK, connection deleted successfully
      
  /followings:
    get:
      security:
        - X-CSRF-TOKEN: []
        - jwtAuth: []
      summary: get following connections
      operationId: get-following-connections
      parameters:
        - name: user_id
          in: query
          required: true
          description: ID to specify the user
          schema:
            type: integer
      responses:
        "200":
          description: OK
          content:
              application/json:
                schema:
                  type: array
                  items:
                    $ref: "#/components/schemas/Connection"
  /followers:
    get:
      security:
        - X-CSRF-TOKEN: []
        - jwtAuth: []
      summary: get followers connections
      operationId: get-follower-connections
      parameters:
        - name: user_id
          in: query
          required: true
          description: ID to specify the user
          schema:
            type: integer
      responses:
        "200":
          description: OK
          content:
              application/json:
                schema:
                  type: array
                  items:
                    $ref: "#/components/schemas/Connection"
  
  /post-likes:
    post:
      security:
        - X-CSRF-TOKEN: []
        - jwtAuth: []
      summary: Create like of Post
      operationId: create-post-like
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/CreatePostLikeReqBody"
      responses:
        "201":
          description: OK
    delete:
      security:
        - X-CSRF-TOKEN: []
        - jwtAuth: []
      summary: delete like of Post
      operationId: delete-post-like
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/DeletePostLikeReqBody"
      responses:
        "204":
          description: OK, connection deleted successfully
  
  /liked-posts:
    get:
      security:
        - X-CSRF-TOKEN: []
        - jwtAuth: []
      summary: Get postID list of User liked
      operationId: get-liked-post-list
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  post_id:
                    type: integer
          
components:
  securitySchemes:
    X-CSRF-TOKEN:
      type: apiKey
      name: X-CSRF-TOKEN
      in: header
    jwtAuth:
      type: apiKey
      name: jwt_token
      in: cookie
    google_auth:
      type: oauth2
      flows:
        authorizationCode:
          authorizationUrl: https://accounts.google.com/o/oauth2/v2/auth
          tokenUrl: https://oauth2.googleapis.com/token
          scopes:
            email: email address
            profile: basic profile information
    state:
      type: apiKey
      name: state
      in: cookie
  schemas:
    ResCsrfToken:
      properties:
        csrf_token:
          type: string
    ReqSignupBody:
      properties:
        username:
          type: string
        identifier:
          type: string
        credential:
          type: string
    ReqLoginBody:
      properties:
          identifier:
            type: string
          credential:
            type: string
    User:
      type: object
      properties:
        user_id:
          type: integer
        name:
          type: string
        profile_image:
          type: string
        profile_text:
          type: string
      required:
      - user_id
      - name
      - profile_image
    UpdateUserReqBody:
      properties:
        name:
          type: string
        profile_image:
          type: string
          format: binary
        profile_text:
          type: string
    Post:
      type: object
      properties:
        post_id:
          type: integer
        user:
          $ref: "#/components/schemas/User"
        content:
          type: string
        rating:
          type: integer
        image:
          type: string
        created_at:
          type: string
        book:
          $ref: "#/components/schemas/Book"
        likes:
          type: array
          items:
            $ref: "#/components/schemas/PostLike"
      required:
      - post_id
      - user
      - content
      - rating
      - created_at
      - book
    ReqCreatePostBody:
      properties:
        content:
          type: string
        rating:
          type: integer
        image:
          type: string
          format: binary
        ISBNcode:
          type: string
      required:
        - content
        - rating
        - ISBNcode
    Book:
      type: object
      properties:
        book_id:
          type: integer
        ISBNcode:
          type: string
        title:
          type: string
        author:
          type: string
        price:
          type: integer
        publisher:
          type: string
        published_at:
          type: string
        item_url:
          type: string
        image:
          type: string
      required:
        - book_id
        - ISBNcode
        - title
        - author
        - price
        - publisher
        - published_at
        - item_url
        - image
    BookGenreNode:
      type: object
      properties:
        id:
          type: integer
        books_genre_id:
          type: string
        books_genre_name:
          type: string
        genre_level:
          type: integer
        parent_genre_id:
          type: string
        children:
          type: array
          items:
            $ref: "#/components/schemas/BookGenreNode"
      required:
        - id
        - books_genre_id
        - books_genre_name
        - genre_level
        - parent_genre_id
        - children
    ChatRoom:
      type: object
      properties:
        room_id:
          type: integer
        target_user_id:
          type: integer
        target_user_name:
          type: string
        target_user_profile_image:
          type: string
        last_message:
          type: string
        last_message_sent_at:
          type: string
      required:
        - room_id
        - target_user_id
        - target_user_name
        - target_user_profile_image
    Message:
      type: object
      properties:
        message_id:
          type: integer
        user_id:
          type: integer
        content:
          type: string
        sent_at:
          type: string
      required:
        - message_id
        - user_id
        - content
        - sent_at
    SendMessageReqBody:
      properties:
        content:
          type: string
        room_id:
          type: integer
      required:
        - content
        - room_id
    Connection:
      properties:
        connection_id:
          type: integer
        target_user_id:
          type: integer
        target_user_name:
          type: string
        target_user_profile_image:
          type: string
      required:
        - connection_id
        - target_user_id
        - target_user_name
        - target_user_profile_image
    PostLike:
      properties:
        post_like_id:
          type: integer
      required:
        - post_like_id
    CreatePostLikeReqBody:
      properties:
        post_id:
          type: integer
      required:
        - post_id
    DeletePostLikeReqBody:
      properties:
        post_id:
          type: integer
      required:
        - post_id
  
    
                  
