openapi: 3.0.0
info:
  version: 1.0.0
  title: ReadersLounge API
  description: ReadersLounge API
servers:
  - url: "http://localhost:8080"
paths:
  /csrftoken:
    get:
      security: []
      summary: get csrf token
      operationId: csrftoken
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ResCsrfToken"
  /signup:
    post:
      security:
        - X-CSRF-TOKEN: []
      summary:  create new user
      operationId: signup
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/ReqSignupBody"
        required: true
      responses:
        "201":
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/User"
  /login:
    post:
      security:
        - X-CSRF-TOKEN: []
      summary: login
      operationId: login
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/ReqLoginBody"
        required: true
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/User"
  /oauth/google/callback:
    get:
      security:
        - google_auth:
          - email
          - profile
        - state: []
      summary: Callback for Google OAuth
      operationId: google_oauth_callback
      parameters:
        - name: state
          in: query
          required: true
          description: State parameter for CSRF protection
          schema:
            type: string
        - name: code
          in: query
          required: true
          description: Authorization code returned by Google auth server
          schema:
            type: string
      responses:
        "302":
          description: Redirect to Home
  /logout:
    post:
      security:
        - X-CSRF-TOKEN: []
      summary: logout
      operationId: logout
      requestBody:
        content:
          application/json:
            schema:
              type: object
      responses:
        "200":
          description: OK
  /user:
    get:
      security:
        - X-CSRF-TOKEN: []
        - jwtAuth: []
      summary: get user
      operationId: user
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/User"
  /posts:
    get:
      security:
        - X-CSRF-TOKEN: []
        - jwtAuth: []
      summary: get posts
      operationId: get-posts
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Post"
    post:
      security:
        - X-CSRF-TOKEN: []
        - jwtAuth: []
      summary: create post
      operationId: create-post
      requestBody:
        content:
          multipart/form-data:
            schema:
              $ref: "#/components/schemas/ReqCreatePostBody"
        required: true
      responses:
        "201":
          description: OK
          
  /books:
    get:
      security:
        - X-CSRF-TOKEN: []
        - jwtAuth: []
      summary: fetch book data from RakutenAPI
      operationId: fetch-book-data
      parameters:
        - name: booksGenreId
          in: query
          description: ID to specify the genre in Rakuten Books
          schema:
            type: string
        - name: keyword
          in: query
          description: keyword to search books
          schema:
            type: string
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Book"
  
  /books-genres:
    get:
      security:
        - X-CSRF-TOKEN: []
        - jwtAuth: []
      summary: fetch book genre from RakutenAPI
      operationId: fetch-book-genres
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/BookGenre"
      
components:
  securitySchemes:
    X-CSRF-TOKEN:
      type: apiKey
      name: X-CSRF-TOKEN
      in: header
    jwtAuth:
      type: apiKey
      name: jwt_token
      in: cookie
    google_auth:
      type: oauth2
      flows:
        authorizationCode:
          authorizationUrl: https://accounts.google.com/o/oauth2/v2/auth
          tokenUrl: https://oauth2.googleapis.com/token
          scopes:
            email: email address
            profile: basic profile information
    state:
      type: apiKey
      name: state
      in: cookie
  schemas:
    ResCsrfToken:
      properties:
        csrf_token:
          type: string
    ReqSignupBody:
      properties:
        username:
          type: string
        identifier:
          type: string
        credential:
          type: string
    ReqLoginBody:
      properties:
          identifier:
            type: string
          credential:
            type: string
    User:
      type: object
      properties:
        user_id:
          type: integer
        name:
          type: string
        profile_image:
          type: string
      required:
      - user_id
      - name
      - profile_image
    Post:
      type: object
      properties:
        post_id:
          type: integer
        user:
          $ref: "#/components/schemas/User"
        content:
          type: string
        rating:
          type: integer
        image:
          type: string
        created_at:
          type: string
        book:
          $ref: "#/components/schemas/Book"
      required:
      - post_id
      - user
      - content
      - rating
      - created_at
      - book
    ReqCreatePostBody:
      properties:
        content:
          type: string
        rating:
          type: integer
        image:
          type: string
          format: binary
        ISBNcode:
          type: string
      required:
        - content
        - rating
        - ISBNcode
    Book:
      type: object
      properties:
        book_id:
          type: integer
        ISBNcode:
          type: string
        title:
          type: string
        author:
          type: string
        price:
          type: integer
        publisher:
          type: string
        published_at:
          type: string
        item_url:
          type: string
        image:
          type: string
    BookGenre:
      type: object
      properties:
        id:
          type: integer
        books_genre_id:
          type: string
        books_genre_name:
          type: string
        genre_level:
          type: integer
        parent_genre_id:
          type: string
        
        
    
                  
