openapi: 3.1.0
info:
  version: 1.0.0
  title: ReadersLounge API
  description: ReadersLounge API
servers:
  - url: "http://localhost:8080"
paths:
  /signup:
    post:
      summary:  create new user
      operationId: signup
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                username:
                  type: string
                identifier:
                  type: string
                credential:
                  type: string
        required: true
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  identifier:
                    type: string
                  credential:
                    type: string
                  
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
