/* tslint:disable */
/* eslint-disable */
/**
 * ReadersLounge API
 * ReadersLounge API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface BookGenre
 */
export interface BookGenre {
    /**
     * 
     * @type {number}
     * @memberof BookGenre
     */
    'id': number;
    /**
     * 
     * @type {string}
     * @memberof BookGenre
     */
    'books_genre_id': string;
    /**
     * 
     * @type {string}
     * @memberof BookGenre
     */
    'books_genre_name': string;
    /**
     * 
     * @type {number}
     * @memberof BookGenre
     */
    'genre_level': number;
    /**
     * 
     * @type {string}
     * @memberof BookGenre
     */
    'parent_genre_id': string;
}

