/* tslint:disable */
/* eslint-disable */
/**
 * ReadersLounge API
 * ReadersLounge API
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 * @interface Book
 */
export interface Book {
  /**
   *
   * @type {number}
   * @memberof Book
   */
  book_id: number;
  /**
   *
   * @type {string}
   * @memberof Book
   */
  ISBNcode: string;
  /**
   *
   * @type {string}
   * @memberof Book
   */
  title: string;
  /**
   *
   * @type {string}
   * @memberof Book
   */
  author: string;
  /**
   *
   * @type {number}
   * @memberof Book
   */
  price: number;
  /**
   *
   * @type {string}
   * @memberof Book
   */
  publisher: string;
  /**
   *
   * @type {string}
   * @memberof Book
   */
  published_at: string;
  /**
   *
   * @type {string}
   * @memberof Book
   */
  item_url: string;
  /**
   *
   * @type {string}
   * @memberof Book
   */
  image: string;
}
