/* tslint:disable */
/* eslint-disable */
/**
 * ReadersLounge API
 * ReadersLounge API
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 * @interface ChatRoom
 */
export interface ChatRoom {
  /**
   *
   * @type {number}
   * @memberof ChatRoom
   */
  room_id: number;
  /**
   *
   * @type {number}
   * @memberof ChatRoom
   */
  target_user_id: number;
  /**
   *
   * @type {string}
   * @memberof ChatRoom
   */
  target_user_name: string;
  /**
   *
   * @type {string}
   * @memberof ChatRoom
   */
  target_user_profile_image: string;
  /**
   *
   * @type {string}
   * @memberof ChatRoom
   */
  last_message?: string;
  /**
   *
   * @type {string}
   * @memberof ChatRoom
   */
  last_message_sent_at?: string;
}
