/* tslint:disable */
/* eslint-disable */
/**
 * ReadersLounge API
 * ReadersLounge API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface CommentLike
 */
export interface CommentLike {
    /**
     * 
     * @type {number}
     * @memberof CommentLike
     */
    'comment_like_id': number;
    /**
     * 
     * @type {number}
     * @memberof CommentLike
     */
    'user_id': number;
}

