/* tslint:disable */
/* eslint-disable */
/**
 * ReadersLounge API
 * ReadersLounge API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import type { Configuration } from '../configuration';
import type { AxiosPromise, AxiosInstance, AxiosRequestConfig } from 'axios';
import globalAxios from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction } from '../common';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, RequestArgs, BaseAPI, RequiredError } from '../base';
// @ts-ignore
import { Post } from '../models';
// @ts-ignore
import { ReqLoginBody } from '../models';
// @ts-ignore
import { ReqSignupBody } from '../models';
// @ts-ignore
import { ResCsrfToken } from '../models';
// @ts-ignore
import { User } from '../models';
/**
 * DefaultApi - axios parameter creator
 * @export
 */
export const DefaultApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @summary create post
         * @param {string} content 
         * @param {number} rating 
         * @param {string} iSBNcode 
         * @param {File} [image] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        createPost: async (content: string, rating: number, iSBNcode: string, image?: File, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'content' is not null or undefined
            assertParamExists('createPost', 'content', content)
            // verify required parameter 'rating' is not null or undefined
            assertParamExists('createPost', 'rating', rating)
            // verify required parameter 'iSBNcode' is not null or undefined
            assertParamExists('createPost', 'iSBNcode', iSBNcode)
            const localVarPath = `/posts`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;
            const localVarFormParams = new ((configuration && configuration.formDataCtor) || FormData)();

            // authentication X-CSRF-TOKEN required
            await setApiKeyToObject(localVarHeaderParameter, "X-CSRF-TOKEN", configuration)

            // authentication jwtAuth required


            if (content !== undefined) { 
                localVarFormParams.append('content', content as any);
            }
    
            if (rating !== undefined) { 
                localVarFormParams.append('rating', rating as any);
            }
    
            if (image !== undefined) { 
                localVarFormParams.append('image', image as any);
            }
    
            if (iSBNcode !== undefined) { 
                localVarFormParams.append('ISBNcode', iSBNcode as any);
            }
    
    
            localVarHeaderParameter['Content-Type'] = 'multipart/form-data';
    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = localVarFormParams;

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary get csrf token
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        csrftoken: async (options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/csrftoken`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary get posts
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getPosts: async (options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/posts`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication X-CSRF-TOKEN required
            await setApiKeyToObject(localVarHeaderParameter, "X-CSRF-TOKEN", configuration)

            // authentication jwtAuth required


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Callback for Google OAuth
         * @param {string} state State parameter for CSRF protection
         * @param {string} code Authorization code returned by Google auth server
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        googleOauthCallback: async (state: string, code: string, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'state' is not null or undefined
            assertParamExists('googleOauthCallback', 'state', state)
            // verify required parameter 'code' is not null or undefined
            assertParamExists('googleOauthCallback', 'code', code)
            const localVarPath = `/oauth/google/callback`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication google_auth required
            // oauth required
            await setOAuthToObject(localVarHeaderParameter, "google_auth", ["email", "profile"], configuration)

            // authentication state required

            if (state !== undefined) {
                localVarQueryParameter['state'] = state;
            }

            if (code !== undefined) {
                localVarQueryParameter['code'] = code;
            }


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary login
         * @param {ReqLoginBody} reqLoginBody 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        login: async (reqLoginBody: ReqLoginBody, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'reqLoginBody' is not null or undefined
            assertParamExists('login', 'reqLoginBody', reqLoginBody)
            const localVarPath = `/login`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication X-CSRF-TOKEN required
            await setApiKeyToObject(localVarHeaderParameter, "X-CSRF-TOKEN", configuration)


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(reqLoginBody, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary logout
         * @param {object} [body] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        logout: async (body?: object, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/logout`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication X-CSRF-TOKEN required
            await setApiKeyToObject(localVarHeaderParameter, "X-CSRF-TOKEN", configuration)


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(body, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary create new user
         * @param {ReqSignupBody} reqSignupBody 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        signup: async (reqSignupBody: ReqSignupBody, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'reqSignupBody' is not null or undefined
            assertParamExists('signup', 'reqSignupBody', reqSignupBody)
            const localVarPath = `/signup`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication X-CSRF-TOKEN required
            await setApiKeyToObject(localVarHeaderParameter, "X-CSRF-TOKEN", configuration)


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(reqSignupBody, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary get user
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        user: async (options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/user`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication X-CSRF-TOKEN required
            await setApiKeyToObject(localVarHeaderParameter, "X-CSRF-TOKEN", configuration)

            // authentication jwtAuth required


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * DefaultApi - functional programming interface
 * @export
 */
export const DefaultApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = DefaultApiAxiosParamCreator(configuration)
    return {
        /**
         * 
         * @summary create post
         * @param {string} content 
         * @param {number} rating 
         * @param {string} iSBNcode 
         * @param {File} [image] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async createPost(content: string, rating: number, iSBNcode: string, image?: File, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.createPost(content, rating, iSBNcode, image, options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
        /**
         * 
         * @summary get csrf token
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async csrftoken(options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<ResCsrfToken>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.csrftoken(options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
        /**
         * 
         * @summary get posts
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getPosts(options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Array<Post>>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getPosts(options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
        /**
         * 
         * @summary Callback for Google OAuth
         * @param {string} state State parameter for CSRF protection
         * @param {string} code Authorization code returned by Google auth server
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async googleOauthCallback(state: string, code: string, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.googleOauthCallback(state, code, options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
        /**
         * 
         * @summary login
         * @param {ReqLoginBody} reqLoginBody 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async login(reqLoginBody: ReqLoginBody, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<User>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.login(reqLoginBody, options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
        /**
         * 
         * @summary logout
         * @param {object} [body] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async logout(body?: object, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.logout(body, options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
        /**
         * 
         * @summary create new user
         * @param {ReqSignupBody} reqSignupBody 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async signup(reqSignupBody: ReqSignupBody, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<User>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.signup(reqSignupBody, options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
        /**
         * 
         * @summary get user
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async user(options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<User>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.user(options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
    }
};

/**
 * DefaultApi - factory interface
 * @export
 */
export const DefaultApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = DefaultApiFp(configuration)
    return {
        /**
         * 
         * @summary create post
         * @param {string} content 
         * @param {number} rating 
         * @param {string} iSBNcode 
         * @param {File} [image] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        createPost(content: string, rating: number, iSBNcode: string, image?: File, options?: any): AxiosPromise<void> {
            return localVarFp.createPost(content, rating, iSBNcode, image, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary get csrf token
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        csrftoken(options?: any): AxiosPromise<ResCsrfToken> {
            return localVarFp.csrftoken(options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary get posts
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getPosts(options?: any): AxiosPromise<Array<Post>> {
            return localVarFp.getPosts(options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Callback for Google OAuth
         * @param {string} state State parameter for CSRF protection
         * @param {string} code Authorization code returned by Google auth server
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        googleOauthCallback(state: string, code: string, options?: any): AxiosPromise<void> {
            return localVarFp.googleOauthCallback(state, code, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary login
         * @param {ReqLoginBody} reqLoginBody 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        login(reqLoginBody: ReqLoginBody, options?: any): AxiosPromise<User> {
            return localVarFp.login(reqLoginBody, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary logout
         * @param {object} [body] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        logout(body?: object, options?: any): AxiosPromise<void> {
            return localVarFp.logout(body, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary create new user
         * @param {ReqSignupBody} reqSignupBody 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        signup(reqSignupBody: ReqSignupBody, options?: any): AxiosPromise<User> {
            return localVarFp.signup(reqSignupBody, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary get user
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        user(options?: any): AxiosPromise<User> {
            return localVarFp.user(options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * DefaultApi - object-oriented interface
 * @export
 * @class DefaultApi
 * @extends {BaseAPI}
 */
export class DefaultApi extends BaseAPI {
    /**
     * 
     * @summary create post
     * @param {string} content 
     * @param {number} rating 
     * @param {string} iSBNcode 
     * @param {File} [image] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DefaultApi
     */
    public createPost(content: string, rating: number, iSBNcode: string, image?: File, options?: AxiosRequestConfig) {
        return DefaultApiFp(this.configuration).createPost(content, rating, iSBNcode, image, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary get csrf token
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DefaultApi
     */
    public csrftoken(options?: AxiosRequestConfig) {
        return DefaultApiFp(this.configuration).csrftoken(options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary get posts
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DefaultApi
     */
    public getPosts(options?: AxiosRequestConfig) {
        return DefaultApiFp(this.configuration).getPosts(options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Callback for Google OAuth
     * @param {string} state State parameter for CSRF protection
     * @param {string} code Authorization code returned by Google auth server
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DefaultApi
     */
    public googleOauthCallback(state: string, code: string, options?: AxiosRequestConfig) {
        return DefaultApiFp(this.configuration).googleOauthCallback(state, code, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary login
     * @param {ReqLoginBody} reqLoginBody 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DefaultApi
     */
    public login(reqLoginBody: ReqLoginBody, options?: AxiosRequestConfig) {
        return DefaultApiFp(this.configuration).login(reqLoginBody, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary logout
     * @param {object} [body] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DefaultApi
     */
    public logout(body?: object, options?: AxiosRequestConfig) {
        return DefaultApiFp(this.configuration).logout(body, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary create new user
     * @param {ReqSignupBody} reqSignupBody 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DefaultApi
     */
    public signup(reqSignupBody: ReqSignupBody, options?: AxiosRequestConfig) {
        return DefaultApiFp(this.configuration).signup(reqSignupBody, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary get user
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DefaultApi
     */
    public user(options?: AxiosRequestConfig) {
        return DefaultApiFp(this.configuration).user(options).then((request) => request(this.axios, this.basePath));
    }
}

