// Package openapi provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/deepmap/oapi-codegen version v1.15.0 DO NOT EDIT.
package openapi

const (
	X_CSRF_TOKENScopes = "X_CSRF_TOKEN.Scopes"
)

// ReqLoginBody defines model for ReqLoginBody.
type ReqLoginBody struct {
	Credential *string `json:"credential,omitempty"`
	Identifier *string `json:"identifier,omitempty"`
}

// ReqSignupBody defines model for ReqSignupBody.
type ReqSignupBody struct {
	Credential *string `json:"credential,omitempty"`
	Identifier *string `json:"identifier,omitempty"`
	Username   *string `json:"username,omitempty"`
}

// ResCsrfToken defines model for ResCsrfToken.
type ResCsrfToken struct {
	CsrfToken *string `json:"csrf_token,omitempty"`
}

// ResSignupBody defines model for ResSignupBody.
type ResSignupBody struct {
	UserId *int `json:"user_id,omitempty"`
}

// LogoutJSONBody defines parameters for Logout.
type LogoutJSONBody = map[string]interface{}

// LoginJSONRequestBody defines body for Login for application/json ContentType.
type LoginJSONRequestBody = ReqLoginBody

// LogoutJSONRequestBody defines body for Logout for application/json ContentType.
type LogoutJSONRequestBody = LogoutJSONBody

// SignupJSONRequestBody defines body for Signup for application/json ContentType.
type SignupJSONRequestBody = ReqSignupBody
