// Package controllers provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/deepmap/oapi-codegen version v1.15.0 DO NOT EDIT.
package controllers

// SignupJSONBody defines parameters for Signup.
type SignupJSONBody struct {
	Credential *string `json:"credential,omitempty"`
	Identifier *string `json:"identifier,omitempty"`
	Username   *string `json:"username,omitempty"`
}

// SignupJSONRequestBody defines body for Signup for application/json ContentType.
type SignupJSONRequestBody SignupJSONBody
