// Package models provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/deepmap/oapi-codegen version v1.15.0 DO NOT EDIT.
package models

// ReqSignupBody defines model for ReqSignupBody.
type ReqSignupBody struct {
	Credential *string `json:"credential,omitempty"`
	Identifier *string `json:"identifier,omitempty"`
	Username   *string `json:"username,omitempty"`
}

// ResSignupBody defines model for ResSignupBody.
type ResSignupBody struct {
	Credential *string `json:"credential,omitempty"`
	Identifier *string `json:"identifier,omitempty"`
}

// SignupJSONRequestBody defines body for Signup for application/json ContentType.
type SignupJSONRequestBody = ReqSignupBody
