name: ReadersLounge Deploy

on:
  push:
    branches:
      - main
    paths:
      - '.github/workflows/deploy.yml'
      - 'backend/**'
      - 'frontend/**'
      - 'infra/terraform/**'

permissions:
  id-token: write
  contents: read

env:
  AWS_REGION: ap-northeast-1

defaults:
  run:
    working-directory: infra/terraform

jobs:
  preview:
    name: "Preview"
    runs-on: ubuntu-latest
    outputs:
      TF_PLAN_EXITCODE: ${{ steps.plan.outputs.exitcode }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform format
        run: terraform fmt -check
      
      - name: Configure AWS Credential
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: ${{ env.AWS_REGION }}
          role-to-assume: ${{ secrets.AWS_IAM_ROLE_ARN }}
      
      - name: Terraform init
        run: terraform init
      
      - name: Terraform validate
        run: |
          terraform validate
      
      - name: Terraform plan
        id: plan
        continue-on-error: true
        run: |
          terraform plan \
            -input=false \
            -detailed-exitcode \
             
